### ISSUE TITLE
Some TODOs:

### ISSUE THREAD

**Issue by jagerman** [oxen-io/oxen-encoding#1]
- [x] get rid of BSD-style licence from the top of source files (since we are LGPLing this)
- [x] Inline the bt_serialize.cpp functions so that the library can be header-only (it is small enough that it seems worthwhile to not have to add an extra linking dependency for projects).
- [x] Rename "oxenenc" (name directory & namespace) to shorter `oxenc`

**Comment by majestrate** [comment]
it is done
